import fs from "node:fs";
import path from "node:path";
import { loadConfig } from "./config";
import { regenerateBarrel } from "./barrel";

// Infrastructure templates (static files written once)
import { renderEventFactory } from "./templates/init-event-factory";
import { renderEventBus } from "./templates/init-event-bus";
import { renderEntityCache } from "./templates/init-entity-cache";
import { renderStateCache } from "./templates/init-state-cache";
import { renderWebSocketProvider } from "./templates/init-websocket-provider";
import { renderSchemasBase } from "./templates/init-schemas-base";
import { renderEntityProjectionTypes } from "./templates/init-entity-projections-types";

// Agent rules (written once to project root — teaches AI agents One River law)
import { renderAgentsMd } from "./templates/init-agents-md";

// Barrel templates (initially empty — regenerated by gen:domain)
import { renderBarrelSchemas } from "./templates/init-barrel-schemas";
import { renderBarrelDispatchers } from "./templates/init-barrel-dispatchers";
import { renderBarrelWsBindings } from "./templates/init-barrel-ws-bindings";
import { renderBarrelEntityProjections } from "./templates/init-barrel-entity-projections";
import { renderBarrelQueryKeys } from "./templates/init-barrel-query-keys";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface InitOptions {
  /** Overwrite existing files (default: false — abort if any file exists). */
  force?: boolean;
}

export interface InitResult {
  ok: boolean;
  filesWritten: string[];
  errors: string[];
}

// ─── File manifest ────────────────────────────────────────────────────────────

interface InitFile {
  /** Relative path from projectRoot. */
  filePath: string;
  /** Returns the file content. */
  render: () => string;
  /** Brief label for logging. */
  label?: string;
}

function buildInitManifest(projectRoot: string): InitFile[] {
  const config = loadConfig(projectRoot);

  return [
    // ── Static infrastructure files (written once, never touched by gen:domain) ──
    {
      filePath: config.api.eventFactoryFile,
      render: renderEventFactory,
      label: "EventFactory service",
    },
    {
      filePath: config.api.eventBusFile,
      render: renderEventBus,
      label: "EventBus service",
    },
    {
      filePath: config.web.entityCacheFile,
      render: () => renderEntityCache(config.sharedPackage),
      label: "entity-cache",
    },
    {
      filePath: config.web.stateCacheFile,
      render: renderStateCache,
      label: "state-cache (lookup table dispatcher)",
    },
    {
      filePath: config.web.providerFile,
      render: renderWebSocketProvider,
      label: "WebSocketProvider (loop-based)",
    },
    // ── Base type files for barrel directories ────────────────────────────────
    {
      filePath: config.api.schemasBaseFile,
      render: renderSchemasBase,
      label: "schemas/_base.ts (envelope Zod schemas)",
    },
    {
      filePath: config.packages.entityProjectionsTypesFile,
      render: renderEntityProjectionTypes,
      label: "entity-projections/_types.ts",
    },
    // ── Initial empty barrels (regenerated after every gen:domain) ────────────
    {
      filePath: config.api.schemasBarrelFile,
      render: () => renderBarrelSchemas([]),
      label: "schemas/_index.ts (barrel, initially empty)",
    },
    {
      filePath: config.web.dispatchersBarrelFile,
      render: () => renderBarrelDispatchers([]),
      label: "domain-dispatchers/_index.ts (barrel, initially empty)",
    },
    {
      filePath: config.web.wsBindingsBarrelFile,
      render: () => renderBarrelWsBindings([]),
      label: "ws-bindings/_index.ts (barrel, initially empty)",
    },
    {
      filePath: config.web.queryKeysBarrelFile,
      render: () => renderBarrelQueryKeys([]),
      label: "query-keys/_index.ts (barrel, initially empty)",
    },
    {
      filePath: config.packages.entityProjectionsBarrelFile,
      render: () => renderBarrelEntityProjections([]),
      label: "entity-projections/_index.ts (barrel, initially empty)",
    },
    // ── Vite-compatible index.ts proxies for _index.ts barrels ───────────────
    // Vite/TypeScript resolves directory imports (e.g. "../lib/query-keys") to
    // index.ts. The generator writes _index.ts barrels, so these thin proxies
    // bridge the gap. They are never overwritten by gen:domain.
    {
      filePath: config.web.queryKeysBarrelFile.replace("_index.ts", "index.ts"),
      render: () => `export * from "./_index";\n`,
      label: "query-keys/index.ts (Vite proxy for _index.ts)",
    },
    {
      filePath: config.web.dispatchersBarrelFile.replace("_index.ts", "index.ts"),
      render: () => `export * from "./_index";\n`,
      label: "domain-dispatchers/index.ts (Vite proxy for _index.ts)",
    },
    {
      filePath: config.web.wsBindingsBarrelFile.replace("_index.ts", "index.ts"),
      render: () => `export * from "./_index";\n`,
      label: "ws-bindings/index.ts (Vite proxy for _index.ts)",
    },
    // ── Agent rules (project root) ────────────────────────────────────────────
    {
      filePath: "AGENTS.md",
      render: renderAgentsMd,
      label: "AGENTS.md (One River rules for AI agents)",
    },
    {
      filePath: "CLAUDE.md",
      render: () => `@AGENTS.md\n`,
      label: "CLAUDE.md (auto-loads AGENTS.md into Claude Code context)",
    },
  ];
}

// ─── Plan display ─────────────────────────────────────────────────────────────

export function renderInitPlan(projectRoot: string): string {
  const manifest = buildInitManifest(projectRoot);
  const config = loadConfig(projectRoot);
  const lines: string[] = [];
  const SEP = "─".repeat(72);
  const CHECK = "✓";
  const CROSS = "✗";
  const INFO = "·";

  lines.push("");
  lines.push("  RiverGen — Initialise Project");
  lines.push(`  Root   : ${projectRoot}`);
  lines.push("");
  lines.push(SEP);
  lines.push("  FILES TO CREATE (infrastructure framework)");
  lines.push(SEP);

  for (const f of manifest) {
    const exists = fs.existsSync(path.join(projectRoot, f.filePath));
    const icon = exists ? CROSS : CHECK;
    const note = exists ? " ← EXISTS (blocked until --force)" : "";
    const label = f.label ? `  [${f.label}]` : "";
    lines.push(`  ${icon}  ${f.filePath}${note}${label}`);
  }

  lines.push("");
  lines.push(SEP);
  lines.push("  WHAT THIS CREATES");
  lines.push(SEP);
  lines.push(
    `  ${INFO}  5 static infrastructure files (EventFactory, EventBus, entity-cache,`,
  );
  lines.push(`       state-cache dispatcher, WebSocketProvider)`);
  lines.push(
    `  ${INFO}  5 empty barrel _index.ts files (regenerated automatically by rivergen gen)`,
  );
  lines.push(
    `  ${INFO}  2 base type files (_base.ts, _types.ts — envelope + projection types)`,
  );
  lines.push("");
  lines.push(`  After init, scaffold your first domain with:`);
  lines.push(`    rivergen gen specs/<domain>.json`);
  lines.push(SEP);
  lines.push("");

  return lines.join("\n");
}

// ─── Idempotency helpers ──────────────────────────────────────────────────────

/**
 * Returns true when the project has already been initialized.
 * Uses entity-cache.ts as the sentinel — it is written by gen:init and never
 * touched by gen:domain, so its presence reliably signals a prior init.
 */
export function isAlreadyInitialized(projectRoot: string): boolean {
  const config = loadConfig(projectRoot);
  return fs.existsSync(path.join(projectRoot, config.web.entityCacheFile));
}

// ─── Execute ──────────────────────────────────────────────────────────────────

export function executeInit(
  projectRoot: string,
  options: InitOptions = {},
): InitResult {
  const result: InitResult = {
    ok: false,
    filesWritten: [],
    errors: [],
  };

  // Guard: abort immediately if already initialized unless --force is passed.
  if (!options.force && isAlreadyInitialized(projectRoot)) {
    console.log(
      "\n  ✗  This project has already been initialized (entity-cache.ts exists).",
    );
    console.log(
      "     Run with --force to overwrite all infrastructure files.\n",
    );
    result.errors.push(
      "Already initialized. Use --force to overwrite existing files.",
    );
    return result;
  }

  const manifest = buildInitManifest(projectRoot);

  const skipped: string[] = [];

  // Write each file — skip existing unless --force
  for (const f of manifest) {
    const absPath = path.join(projectRoot, f.filePath);
    const exists = fs.existsSync(absPath);

    if (exists && !options.force) {
      skipped.push(f.filePath);
      const label = f.label ? `  [${f.label}]` : "";
      console.log(`  ✗  ${f.filePath} ← skipped (exists)${label}`);
      continue;
    }

    try {
      fs.mkdirSync(path.dirname(absPath), { recursive: true });
      fs.writeFileSync(absPath, f.render(), "utf-8");
      result.filesWritten.push(f.filePath);
      const label = f.label ? `  [${f.label}]` : "";
      console.log(`  ✓  ${f.filePath}${label}`);
    } catch (err) {
      result.errors.push(
        `Failed to write ${f.filePath}: ${(err as Error).message}`,
      );
      return result;
    }
  }

  if (skipped.length > 0 && !options.force) {
    console.log(
      `\n  ${skipped.length} file(s) skipped (already exist). Use --force to overwrite.`,
    );
  }

  result.ok = result.errors.length === 0;
  return result;
}
