import type { DomainNames } from "../naming.js";

/**
 * Template: domain-slice-entity-projection
 *
 * Produces: packages/shared/src/entity-projections/<domain>.ts
 *
 * Generated per-domain by rivergen gen.
 * Edit freely — regenerateBarrel() only ever rewrites _index.ts, not this file.
 *
 * Declares how entity-cache.ts updates React Query caches for each entity type
 * in this domain (onCreate / onUpdate / onDelete key factories + invalidations).
 */
export function renderDomainEntityProjectionSlice(n: DomainNames): string {
  const exportName = `${camelCase(n.domainKey)}Projections`;
  const keysName = `${n.entityKey}Keys`;
  // Pluralize naively: append 's' (human can fix edge-cases like "category" → "categories")
  const pluralKey = `${n.entityKey}s`;

  // Extract the room-scoping variable from the room template (e.g. "project:${projectId}" → "projectId").
  // The list cache key must include this variable so WS projections write to the correct scoped entry.
  const roomVarMatch = n.roomTemplate.match(/\$\{(\w+)\}/);
  const roomVar = roomVarMatch ? roomVarMatch[1] : null;

  const onCreateRequired = roomVar
    ? `[
        (_entity, context) => [
          "${pluralKey}",
          "list",
          ((context as Record<string, unknown>)?.${roomVar} as string) ?? "",
        ],
      ]`
    : `[() => ["${pluralKey}"]]`;

  const onUpdateRequired = roomVar
    ? `[
        (_entity, context) => [
          "${pluralKey}",
          "list",
          ((context as Record<string, unknown>)?.${roomVar} as string) ?? "",
        ],
      ]`
    : `[() => ["${pluralKey}"]]`;

  return `import type { EntityProjectionEntry } from "./_types";

// Entity projection registry for the ${n.domainDisplay} domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Keys must match what ${keysName}.list(${roomVar ? `{ ${roomVar} }` : '{}'}) returns:
//   ${roomVar ? `["${pluralKey}", "list", ${roomVar}]` : `["${pluralKey}"]`}

export const ${exportName}: Record<string, EntityProjectionEntry> = {
  ${n.entityKey}: {
    ownedKeyFactories: ["${keysName}"],
    onCreate: { required: ${onCreateRequired}, invalidate: [] },
    onUpdate: { required: ${onUpdateRequired}, invalidate: [] },
    onDelete: { invalidate: [["${pluralKey}"]] },
  },
};
`;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
