import type { DomainNames } from "../naming";

/**
 * Template: domain-slice-schemas
 *
 * Produces: apps/api/src/lib/event-factory/schemas/<domain>.ts
 *
 * Generated per-domain by rivergen gen.
 * Edit freely — regenerateBarrel() only ever rewrites _index.ts, not this file.
 * Add one entry per event type you publish via EventFactory.
 */
export function renderDomainSchemaSlice(n: DomainNames): string {
  const exportName = `${camelCase(n.domainKey)}Schemas`;

  const entries = n.events
    .map((ev) => {
      // Infer the ID field from the entity key
      const idField = `${n.entityKey}Id`;
      return `  "${ev}": z.object({ ${idField}: stringId }).strict(),`;
    })
    .join("\n");

  return `import { z } from "zod";

// ${n.domainDisplay} event payload schemas
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Each key corresponds to an event name you pass to EventFactory.publish().
// The matching .strict() Zod schema is validated at publish time.
// If you add a field here, add it to your EventFactory.publish() call too.

const stringId = z.string().min(1);

export const ${exportName}: Record<string, z.ZodTypeAny> = {
${entries}
};
`;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
