import type { DomainNames } from "../naming";

/**
 * Template: domain-slice-entity-projection
 *
 * Produces: packages/shared/src/entity-projections/<domain>.ts
 *
 * Generated per-domain by rivergen gen.
 * Edit freely — regenerateBarrel() only ever rewrites _index.ts, not this file.
 *
 * Declares how entity-cache.ts updates React Query caches for each entity type
 * in this domain (onCreate / onUpdate / onDelete key factories + invalidations).
 */
export function renderDomainEntityProjectionSlice(n: DomainNames): string {
  const exportName = `${camelCase(n.domainKey)}Projections`;
  const keysName = `${n.entityKey}Keys`;
  // Pluralize naively: append 's' (human can fix edge-cases like "category" → "categories")
  const pluralKey = `${n.entityKey}s`;

  return `import type { EntityProjectionEntry } from "./_types";

// Entity projection registry for the ${n.domainDisplay} domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Each key is a camelCase entity name (same key used in applyEntityCreate/Update/Delete).
// ownedKeyFactories: query key factory names that "own" this entity.
// onCreate / onUpdate: required = cache keys to ADD/REPLACE entity in.
//                      invalidate = additional queries to refetch.
// onDelete: invalidate = query keys whose cache is cleared when entity is deleted.
//
// TODO: update query key arrays to match your domain's actual query key structure.

export const ${exportName}: Record<string, EntityProjectionEntry> = {
  ${n.entityKey}: {
    ownedKeyFactories: ["${keysName}"],
    onCreate: { required: [() => ["${pluralKey}"]], invalidate: [] },
    onUpdate: { required: [() => ["${pluralKey}"]], invalidate: [] },
    onDelete: { invalidate: [["${pluralKey}"]] },
  },
};
`;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
