import type { DomainNames } from "../naming";

/**
 * Template: domain-slice-query-keys
 *
 * Produces: apps/web/src/lib/query-keys/<domain>.ts
 *
 * Generated per-domain by rivergen gen.
 * Edit freely — regenerateBarrel() only ever rewrites _index.ts, not this file.
 *
 * Exports a <entityKey>Keys factory object. Components and mutations import it
 * via `import { <entityKey>Keys } from "@/lib/query-keys"` (barrel re-export).
 *
 * NEVER hardcode cache key strings — always use these factories.
 */
export function renderDomainQueryKeysSlice(n: DomainNames): string {
  const keysName = `${n.entityKey}Keys`;
  // Plural base label used as the first segment of every key
  const base = `${n.entityKey}s`;

  // Parse ${varName} placeholders from room template.
  // e.g. "project:${projectId}" → ["projectId"]
  // These become the typed context parameters on list(), scoping the cache key
  // to the same room scope used by WS projections.
  const roomVars = [...n.roomTemplate.matchAll(/\$\{(\w+)\}/g)].map(
    (m) => m[1],
  );

  const listFactory =
    roomVars.length > 0
      ? `list: (ctx: { ${roomVars.map((v) => `${v}: string`).join("; ")} }) => ["${base}", "list", ${roomVars.map((v) => `ctx.${v}`).join(", ")}] as const`
      : `list: () => ["${base}", "list"] as const`;

  const ctxComment =
    roomVars.length > 0
      ? `// list() scope mirrors room template: ${n.roomTemplate}\n`
      : "";

  return `// Query key factory for the ${n.domainDisplay} domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Import via: import { ${keysName} } from "@/lib/query-keys"
// These factories are the ONLY way to reference this entity's cache scope.
// Hardcoding ["${base}", ...] strings anywhere else is a Gate #10 violation.
${ctxComment}
export const ${keysName} = {
  all: () => ["${base}"] as const,
  ${listFactory},
  detail: (id: string) => ["${base}", "detail", id] as const,
};
`;
}
}
