import type { DomainNames } from "../naming";

/**
 * Template: domain-slice-query-keys
 *
 * Produces: apps/web/src/lib/query-keys/<domain>.ts
 *
 * Generated per-domain by rivergen gen.
 * Edit freely — regenerateBarrel() only ever rewrites _index.ts, not this file.
 *
 * Exports a <entityKey>Keys factory object. Components and mutations import it
 * via `import { <entityKey>Keys } from "@/lib/query-keys"` (barrel re-export).
 *
 * NEVER hardcode cache key strings — always use these factories.
 */
export function renderDomainQueryKeysSlice(n: DomainNames): string {
  const keysName = `${n.entityKey}Keys`;
  // Plural base label used as the first segment of every key
  const base = `${n.entityKey}s`;

  return `// Query key factory for the ${n.domainDisplay} domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Import via: import { ${keysName} } from "@/lib/query-keys"
// These factories are the ONLY way to reference this entity's cache scope.
// Hardcoding ["${base}", ...] strings anywhere else is a Gate #10 violation.

export const ${keysName} = {
  all: () => ["${base}"] as const,
  list: () => ["${base}", "list"] as const,
  detail: (id: string) => ["${base}", "detail", id] as const,
};
`;
}
