import type { DomainNames } from "../naming";

/**
 * Template: domain-slice-dispatchers
 *
 * Produces: apps/web/src/lib/cache/domain-dispatchers/<domain>.ts
 *
 * Generated per-domain by rivergen gen.
 * Edit freely — regenerateBarrel() only ever rewrites _index.ts, not this file.
 *
 * Maps each event name to a call into the domain's projection file.
 * state-cache.ts looks up the eventName in domainDispatchers and calls it.
 */
export function renderDomainDispatcherSlice(n: DomainNames): string {
  const exportName = `${camelCase(n.domainKey)}Dispatchers`;
  const projectionImport = `../../projections/${n.domainKey}-projections`;

  // Derive individual function names from events: "doc.created" → "applyDocCreated"
  const fnNames = n.events.map((ev) => {
    const action = ev
      .split(".")
      .slice(1)
      .join("-")
      .split("-")
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("");
    return `apply${n.entityPascal}${action}`;
  });

  const imports = fnNames.join(",\n  ");

  const entries = n.events
    .map(
      (ev, i) =>
        `  "${ev}": (payload, qc) => ${fnNames[i]}(payload as Record<string, unknown>, qc),`,
    )
    .join("\n");

  return `import { QueryClient } from "@tanstack/react-query";
import {
  ${imports},
} from "${projectionImport}";

type AnyPayload = Record<string, unknown> | null | undefined;

// Dispatch map for the ${n.domainDisplay} domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Add an entry for every event the domain emits. The key must be the exact
// event name string (dot notation). The value calls into the domain projection.

export const ${exportName}: Record<
  string,
  (payload: AnyPayload, queryClient: QueryClient) => void
> = {
${entries}
};
`;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
