import type { DomainNames } from "../naming";

/**
 * Template: domain-slice-ws-bindings
 *
 * Produces: apps/web/src/providers/ws-bindings/<domain>.ts
 *
 * Generated per-domain by rivergen gen.
 * Edit freely — regenerateBarrel() only ever rewrites _index.ts, not this file.
 *
 * Lists every Socket.IO event name that the backend emits for this domain.
 * WebSocketProvider reads getAllWsBindings() to register socket.on() handlers.
 * Entries here must 1:1 match what eventBus listeners emit on the backend.
 */
export function renderDomainWsBindingsSlice(n: DomainNames): string {
  const exportName = `${camelCase(n.domainKey)}WsBindings`;

  const entries = n.events.map((ev) => `  "${ev}",`).join("\n");

  return `// Socket.IO event bindings for the ${n.domainDisplay} domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Every string here must match the event name the backend emits via socket.emit().
// WebSocketProvider loops over getAllWsBindings() and registers routeEvent() for each.

export const ${exportName}: string[] = [
${entries}
];
`;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
