/**
 * Template: init-barrel-entity-projections
 *
 * Produces: packages/shared/src/entity-projections/_index.ts
 *
 * Written by rivergen init (initially empty).
 * Regenerated atomically by regenerateBarrel() after every rivergen gen.
 *
 * Re-exports the shared types (QueryKey, ProjectionFn, EntityProjectionEntry)
 * so downstream code only needs to import from entity-projections/_index.
 */

export function renderBarrelEntityProjections(domainKeys: string[]): string {
  const imports = domainKeys
    .map((d) => `import { ${camelCase(d)}Projections } from "./${d}";`)
    .join("\n");

  const spread = domainKeys
    .map((d) => `  ...${camelCase(d)}Projections,`)
    .join("\n");

  return `${domainKeys.length > 0 ? imports + "\n" : ""}
// Shared types — re-exported so consumers only import from this barrel
export type {
  QueryKey,
  ProjectionFn,
  EntityProjectionEntry,
} from "./_types";

/**
 * Registry of all entity projections across all domains.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export const ENTITY_PROJECTIONS: Record<string, import("./_types").EntityProjectionEntry> = {
${spread || "  // no domains registered yet"}
};
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
