/**
 * Template: init-barrel-query-keys
 *
 * Produces: apps/web/src/lib/query-keys/_index.ts
 *
 * Written by rivergen init (initially empty).
 * Regenerated atomically by regenerateBarrel() after every rivergen gen.
 * Re-exports all domain key factory objects so components and mutations
 * can import from "~/lib/query-keys" (or "@/lib/query-keys") without
 * knowing which file each domain lives in.
 */

export function renderBarrelQueryKeys(domainKeys: string[]): string {
  const lines = domainKeys.map((d) => `export * from "./${d}";`).join("\n");

  return `/**
 * Centralized query-keys barrel — re-exports all domain key factories.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
${lines || "// no domains registered yet"}
`;
}
