import { QueryClient } from "@tanstack/react-query";

/**
 * Template: init-barrel-dispatchers
 *
 * Produces: apps/web/src/lib/cache/domain-dispatchers/_index.ts
 *
 * Written by rivergen init (initially empty).
 * Regenerated atomically by regenerateBarrel() after every rivergen gen.
 * Exports domainDispatchers — a flat event-to-handler map consumed by
 * state-cache.ts's applyRealtimeEventToCache lookup.
 */

type AnyPayload = Record<string, unknown> | null | undefined;
type DispatchHandler = (payload: AnyPayload, queryClient: QueryClient) => void;

export function renderBarrelDispatchers(domainKeys: string[]): string {
  const imports = domainKeys
    .map((d) => `import { ${camelCase(d)}Dispatchers } from "./${d}";`)
    .join("\n");

  const spread = domainKeys
    .map((d) => `  ...${camelCase(d)}Dispatchers,`)
    .join("\n");

  return `import { QueryClient } from "@tanstack/react-query";
${domainKeys.length > 0 ? "\n" + imports + "\n" : ""}
type AnyPayload = Record<string, unknown> | null | undefined;

/**
 * Flat event-name → handler map.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export const domainDispatchers: Record<
  string,
  (payload: AnyPayload, queryClient: QueryClient) => void
> = {
${spread || "  // no domains registered yet"}
};
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
