/**
 * Template: init-barrel-ws-bindings
 *
 * Produces: apps/web/src/providers/ws-bindings/_index.ts
 *
 * Written by rivergen init (initially empty — no events).
 * Regenerated atomically by regenerateBarrel() after every rivergen gen.
 * Exports getAllWsBindings() consumed by WebSocketProvider's event loop.
 */

export function renderBarrelWsBindings(domainKeys: string[]): string {
  const imports = domainKeys
    .map((d) => `import { ${camelCase(d)}WsBindings } from "./${d}";`)
    .join("\n");

  const spread = domainKeys
    .map((d) => `  ...${camelCase(d)}WsBindings,`)
    .join("\n");

  return `${domainKeys.length > 0 ? imports + "\n" : ""}
/**
 * Returns the flat list of all Socket.IO event names that WebSocketProvider
 * should bind a routeEvent handler to.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export function getAllWsBindings(): string[] {
  return [
${spread || "    // no domains registered yet"}
  ];
}
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
