import { z } from "zod";

/**
 * Template: init-barrel-schemas
 *
 * Produces: apps/api/src/lib/event-factory/schemas/_index.ts
 *
 * Written by rivergen init (initially with no domains).
 * Regenerated atomically by regenerateBarrel() after every rivergen gen.
 * Re-exports base types from _base.ts so event-factory.service.ts only
 * needs to import from ./schemas/_index.
 */

export function renderBarrelSchemas(domainKeys: string[]): string {
  const imports = domainKeys
    .map((d) => `import { ${camelCase(d)}Schemas } from "./${d}";`)
    .join("\n");

  const spread = domainKeys
    .map((d) => `  ...${camelCase(d)}Schemas,`)
    .join("\n");

  return `import { z } from "zod";
${domainKeys.length > 0 ? "\n" + imports + "\n" : ""}
// Base envelope/actor/context/origin schemas and their types
export {
  EventActorSchema,
  EventContextSchema,
  EventOriginSchema,
  EventEnvelopeSchema,
  type EventActor,
  type EventContext,
  type EventOrigin,
  type EventEnvelope,
} from "./_base";

/**
 * Merged payload schema map — every event type registered across all domain slices.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export const EventPayloadSchemas: Record<string, z.ZodTypeAny> = {
${spread || "  // no domains registered yet"}
};
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
